services:
  app:
    image: ${DOCKER_IMAGE}
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '8g'
        reservations:
          cpus: '1'
          memory: '6g'

  cache-redis:
    image: redis:7.4
    restart: always
    container_name: cache-redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '2g'
        reservations:
          cpus: '0.3'
          memory: '1g'