# Docker Compose file for setting up a Spring Boot application with PostgreSQL
# - Defines two services: app (Spring Boot) and db (PostgreSQL)
# - Configures resource limits and reservations for the app
# - Uses a shared volume for persistent PostgreSQL data

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file: "local.env"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '8g'
        reservations:
          cpus: '1'
          memory: '6g'
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - local.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
