# Development configuration for the `dev` profile.
# - Datasource: Configures the PostgreSQL connection.
# - JPA: Sets Hibernate to auto-update schema and shows SQL in logs.
# - SQL Init: Always runs SQL script on startup from the specified location.
# - Thymeleaf: Disables caching for easier template updates.
# - DevTools: Enables LiveReload and specifies directories to exclude from auto-restart.
# - H2 Console: Disabled as it's not needed in development.
#
# Refer to the `.docker-dev.env` file for examples of environment variables used in these settings.

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:postgres.sql

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      exclude:
        - static/**,public/**
      additional-exclude:
        - custom-dir/**,another-dir/**

  h2:
    console:
      enabled: false
