spring:
  application:
    name: GZGestao
  profiles:
    active: dev

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

logging:
  level:
    org:
      springframework:
        security: DEBUG
