spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:postgres.sql

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      exclude:
        - static/**,public/**
      additional-exclude:
        - custom-dir/**,another-dir/**

  h2:
    console:
      enabled: false
