spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: false

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: false


logging:
  level:
    org:
      springframework:
        security: info
      hibernate: info
    com:
      zaxxer:
        hikari: info
