spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:h2.sql

logging:
  level:
    org:
      springframework:
        security: DEBUG
# keys test
jwt:
  public:
    key: "-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAySoeWQSGMp8mz/fVjQOr
a1a9VC199RK8DyvfFLTrmZt9izJQg9tpJh7P9qFki+sBmAtu+0FjacGRjPqOZhHG
niYamZFadUzEihYj5HsbB+WUpsBOA6qg04QopEjRXNPUI58s1LHBBXJFUIGQcdSo
dsSculzu7ya8GJRxY5NaQ5P2bzM66VmSjFUaOgIlCqR+Hwst6G7Vv9SpsROhecG9
L9W4qnCI5uEjBxZDohyY40klarD9Tq4qe4+NqHuL4uzfQzPI84k53K/NBPv9q0WK
E7at3htv2pvMRJ4bQHauE+dBbfEnyRrhUkTtrf2wOphgzieTqQWr/zCnxeXX1wrw
7wIDAQAB
-----END PUBLIC KEY-----
"
  private:
    key: "-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDJKh5ZBIYynybP
99WNA6trVr1ULX31ErwPK98UtOuZm32LMlCD22kmHs/2oWSL6wGYC277QWNpwZGM
+o5mEcaeJhqZkVp1TMSKFiPkexsH5ZSmwE4DqqDThCikSNFc09QjnyzUscEFckVQ
gZBx1Kh2xJy6XO7vJrwYlHFjk1pDk/ZvMzrpWZKMVRo6AiUKpH4fCy3obtW/1Kmx
E6F5wb0v1biqcIjm4SMHFkOiHJjjSSVqsP1Orip7j42oe4vi7N9DM8jziTncr80E
+/2rRYoTtq3eG2/am8xEnhtAdq4T50Ft8SfJGuFSRO2t/bA6mGDOJ5OpBav/MKfF
5dfXCvDvAgMBAAECggEALxbB5dqOQ1lH75S3E3xRax3x0buYaX7KMM73OFSldd6V
A7lyaXs54OeDjNr4u1v2ko3Sm9QRnlbmaFbacIAmuyx2O45v21duBljqa/h5Ol7+
bg5D9M3DOeAM13AIOi+H0BLZnqxBX7IBEbhShKLgEHUzrthEQg0SKLrO1B1RGtIk
gwPhBPqem/trbTwTcc2k6w4ivdD6MXyY/ph7romC89KIQKUQw4xS86F/JSNnp9hX
ynz1YcT64Z+tV0071yFkBZlYyrvMQNobXa01Nh8ZOg5x6/rZR+/3c+FbnFV4i+dv
0SGY9flEtrRW0hWKNA89/dgRb8xsINXX8WOqqrChyQKBgQDVZQLdm1wC974Pe8wN
bcBBuClX1mJkXaMLqnQqhykvfAHDEeTowMCROmMt5sKaEhzp+r3JlU066PZBlPWz
Ah304ntvfNL3lsZhZE7HTix952v3FzLIP7b6gk9LGFUw9SohrLVgLnPGp862a+eL
olj/bDsJ1mLA9FJUkeRnxVdRlQKBgQDxVAHOaeGIdism1WGvUba3tZyrs8UfBiIo
JLxLsZzAJIJftSAefrf7WPt2I/jHT5iJ9DN71aQTH4wU13Sj487hLutFybz3pz4r
75CLoVxGYDHiNPtsb3glJeagRPLMtlfev47QcFi6pcWSafJLN0Dl6WP7P6gtBQ/O
fC9LJp9fcwKBgH4uHGOtWdrnYxsEuMO4AdbabpfhzIxMUfyz7by370KEsQYHrrNy
RmuZesvJh4hS7YXtHgv0nJYY6oQc8KvItK34vcROqvB71xH/nhV7xBMupEiXDxAZ
nLjEFN7ypG0uipse5KDa1trAnxp+84s9lCJ0fPR0MDCoR4Z6PfSeW+OBAoGANRaG
4zKVo6BjM8LDH385U8aG9ZqxZXbC8tPJ/FjRI8+kQoukyjCUJp3Xi5C0PJw88TQg
U0CXPIG3HiqbhSYrL4xTw2FyyYQoACBOSvkvRGgK8Tk4ig0nf/yLdHxWcUQ3pk+7
igz85+ppwSC/ZV59T1Z9YRsK0wSHCqR0/vI7IxMCgYEAmH02URG/aViWeuhPbEOJ
Nqt3wWMsHBNDA94zJcgN8SvZTMjTmoXTRpiBkkLyNAK7qPUlMcJYs6SG3dOknnag
KhweVTDSLw0lBzsjbGvCmKnE+yNq1R7CNg5Yt5QSPdqH9NsDCApC2SDY8r7IZzRN
MftguRcY6cB+nqdpJtSsFdE=
-----END PRIVATE KEY-----
"