spring:
  application:
    name: GZGestao
  profiles:
    active: test

jwt:
  public:
    key: ${JWT_PUBLIC_KEY}
  private:
    key: ${JWT_PRIVATE_KEY}

logging:
  level:
    org:
      springframework:
        security: DEBUG
