# Test configuration for the `test` profile.
# - Datasource: Configures an in-memory H2 database for testing.
# - JPA: Creates and drops the schema automatically for each test run; shows SQL in logs.
# - SQL Init: Always runs the SQL script on startup from the specified location.
# - JWT: Loads public and private keys for JWT. Note: For tests to work correctly, these keys need to be hardcoded in this file or provided via test-specific environment variables.
# - Logging: Sets DEBUG level logging for Spring Security to aid in testing.

# Refer to the `.docker-dev.env` file for examples of environment variables like JWT_PUBLIC_KEY and JWT_PRIVATE_KEY.

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true


jwt:
  public:
    key: ${JWT_PUBLIC_KEY}
  private:
    key: ${JWT_PRIVATE_KEY}

logging:
  level:
    root: info
    org.springframework.security: warn