# Test profile configuration for GZGestao application.
# - Activates the test profile and sets application name.
# - Loads JWT keys from environment variables for testing.
# - Sets logging level to DEBUG for Spring Security.

spring:
  application:
    name: GZGestao
  profiles:
    active: test

jwt:
  public:
    key: ${JWT_PUBLIC_KEY}
  private:
    key: ${JWT_PRIVATE_KEY}

logging:
  level:
    root: INFO
    org.springframework.security: INFO
