name: Test SSH Command

on:
  push:
    branches:
      - master  # Branch que aciona o teste

jobs:
  test-ssh-command:
    runs-on: ubuntu-latest
    environment: gzgestaoprod

    steps:
    - name: Run command on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.VPS_PORT }}  # Padrão é 22, altere se necessário
        script: |
          echo "Testando conexão SSH e execução de comandos"
