name: Test SCP Upload

on:
  push:
    branches:
      - master  # Branch que aciona o teste

jobs:
  test-scp-upload:
    runs-on: ubuntu-latest
    environment: gzgestaoprod

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Upload files to VPS using SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.VPS_PORT }}  # Padrão é 22, altere se necessário
        source: "./*"  # Envia todos os arquivos do diretório atual
        target: "/home/deploy/gzgestao"  # Caminho de destino na VPS
