# This workflow builds a Java project with Maven and caches dependencies to improve execution time.
# It also sets up a PostgreSQL service for integration tests during the build process.

name: Build

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: database
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml -Pdev -DskipTests
      env:
        SPRING_PROFILES_ACTIVE: dev
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/database
        SPRING_DATASOURCE_USERNAME: user
        SPRING_DATASOURCE_PASSWORD: password
        JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
        JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
