# GitHub Actions Workflow: Unit Tests
# - Runs on push or pull request to the master and dev branches.
# - Sets up JDK 21 and runs unit tests using Maven with the test profile.

name: Unit Tests

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run tests with Maven
      run: mvn test -B -Dspring.profiles.active=test
      env:
        JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
        JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}

